# Generated by Django 5.1.5 on 2025-02-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm1_0', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10_0', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
